### ISSUE TITLE
Template Engine need to be decided

### ISSUE THREAD

**Issue by leituo56** [radapter/iTravel#2]
We need to decide template engine.
Feel free to leave comments here.

Close this issue after push the code

**Comment by jiangxiaoli** [comment]
We are going to use Angular, so may use its default template. As SPA, the template doesn't need to be defined in server side. So for server side, link to the index.html page is sufficient.

**Comment by leituo56** [comment]
So I think EJS will reserve HTML format. SPA will also need some non-public pages which would be easy to handle by server rendering template, so I'll set ejs for template engine by now. I would change this by next commit

**Comment by leituo56** [comment]
Issue closed. Reopen if need other modifications.
@jiangxiaoli I change from jade to ejs in commit f583034
