### ISSUE TITLE
navbar ng-show/ng-hide not working

### ISSUE THREAD

**Issue by jiangxiaoli** [radapter/iTravel#20]
Two sets of navbar to landing page and others.
Cant switch between them with $scope variable. 

Now using a mix of these two stylings. will cause a navbar-fixed-top issue for content margin top

Temp solution for content margin issue: 

```
.jumbotron{
  margin-top: 60px;
}
```

Please pay attention when using jumbotron class

**Comment by IndieDevYulin** [comment]
@jiangxiaoli , which branch is problem on?

**Comment by jiangxiaoli** [comment]
i was working on landing-ui, it has already merged to develop.

**Comment by jiangxiaoli** [comment]
@yye0528 fixed with ng-class, thanks!
